version: '3.8'

services:
  app1:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=mysql
      - USER=root
      - PASSWORD=your_root_password
      - DATABASE=nutech_db
      - SALTROUNDS=10
      - ACCESS_TOKEN_SECRET=your_access_token_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
      - PORT=3000
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  app2:
    build: .
    ports:
      - "3001:3000"
    environment:
      - HOST=mysql
      - USER=root
      - PASSWORD=your_root_password
      - DATABASE=nutech_db
      - SALTROUNDS=10
      - ACCESS_TOKEN_SECRET=your_access_token_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
      - PORT=3000
    depends_on:
      mysql:
        condition: service_healthy

  app3:
    build: .
    ports:
      - "3002:3000"
    environment:
      - HOST=mysql
      - USER=root
      - PASSWORD=your_root_password
      - DATABASE=nutech_db
      - SALTROUNDS=10
      - ACCESS_TOKEN_SECRET=your_access_token_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
      - PORT=3000
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_DATABASE: "nutech_db"
      MYSQL_ROOT_PASSWORD: "your_root_password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3

volumes:
  mysql_data: